### ISSUE TITLE
first column in the pricing table isn't lining up properly with the others.

### ISSUE THREAD

**Issue by deskspace** [unetics/ECHO#5]
Not sure whether this is a theme issue or not, but the first column in the pricing table isn't lining up properly with the others.  After a very quick fiddle I haven't yet spotted the problem CSS.

![screen shot 2015-06-05 at 2 47 36 pm](https://cloud.githubusercontent.com/assets/12410039/7999630/da9af020-0b91-11e5-801b-074100ed90aa.png)

**Comment by unetics** [comment]
i believe this is only due to the title length i will not be fixing as is an external plugin but i do have our own replacement in the works

**Comment by deskspace** [comment]
Okay, I'll look into it further and see if I can solve it in this single
case with CSS or some other trickery.

**Comment by unetics** [comment]
more then happy to help with the single case fix

**Comment by unetics** [comment]
fixed
